export const opcionesDependencia = [
  { value: '0', label: 'No Aplica' },
  { value: '1', label: 'CEA' },
  { value: '2', label: 'CEI' },
  { value: '3', label: 'CENTRO DE CAPACITACION FORMACION E INVESTIGACION PARA LA SEGURIDAD DEL ESTADO DE QUERETARO' },
  { value: 'COBAQ', label: 'COBAQ' },
  { value: 'CECYTEQ', label: 'COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS DEL ESTADO' },
  { value: '6', label: 'COMISION ESTATAL DEL SISTEMA PENITENCIARIO DE QUERETARO' },
  { value: 'CONALEP', label: 'CONALEP' },
  { value: '8', label: 'DIRECCIÓN DE DESARROLLO INTEGRAL DE LA FAMILIA' },
  { value: '9', label: 'DIRECCIÓN DEL REGISTRO PUBLICO DE LA PROPIEDAD' },
  { value: '10', label: 'FISCALIA GENERAL DEL ESTADO' },
  { value: '11', label: 'INSTITUTO DE CAPACITACION PARA EL TRABAJO DEL ESTADO DE QUERETARO' },
  { value: '12', label: 'INSTITUTO DEL DEPORTE Y LA RECREACION DEL ESTADO DE QUERETARO' },
  { value: '13', label: 'INSTITUTO QUERETANO DE LA MUJER' },
  { value: '14', label: 'INSTITUTO QUERETANO DEL TRANSPORTE' },
  { value: '15', label: 'JAPAM' },
  { value: '16', label: 'TRIBUNAL DE CONCILIACION Y ARBITRAJE' },
  { value: '17', label: 'TRIBUNAL DE JUSTICIA ADMINISTRATIVA DEL ESTADO DE QUERETARO' },
  { value: '18', label: 'UTEQ' },
  { value: '19', label: 'UTSJR' },
  { value: '20', label: 'CASA QUERETANA DE LAS ARTESANÍAS' },
  { value: '21', label: 'COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS DEL ESTADO' },
  { value: '22', label: 'COORDINACION DE COMUNICACIÓN SOCIAL' },
  { value: '23', label: 'DIRECCIÓN DE DESARROLLO INTEGRAL DE LA FAMILIA' },
  { value: '24', label: 'DIRECCIÓN DEL REGISTRO PUBLICO DE LA PROPIEDAD' },
  { value: '25', label: 'DIRECCIÓN GENERAL DEL REGISTRO CIVIL' },
  { value: '26', label: 'ESCUELA NORMAL DEL ESTADO' },
  { value: '27', label: 'ESCUELA NORMAL SUPERIOR DE QUERETARO' },
  { value: '28', label: 'INSTITUTO DE CAPACITACION PARA EL TRABAJO DEL ESTADO DE QUERETARO' },
  { value: '29', label: 'INSTITUTO DEL DEPORTE Y LA RECREACION DEL ESTADO DE QUERETARO' },
  { value: '30', label: 'INSTITUTO QUERETANO DE LA CULTURA Y LAS ARTES' },
  { value: '31', label: 'OFICIALÍA MAYOR' },
  { value: '32', label: 'PROCURADURIA GENERAL DE JUSTICIA' },
  { value: '33', label: 'SECRETARÍA DE CULTURA' },
  { value: '34', label: 'SECRETARÍA DE DESARROLLO AGROPECUARIO' },
  { value: '35', label: 'SECRETARÍA DE DESARROLLO SUSTENTABLE' },
  { value: '36', label: 'SECRETARÍA DE DESARROLLO URBANO Y OBRAS PÚBLICAS' },
  { value: '37', label: 'SECRETARÍA DE EDUCACIÓN' },
  { value: '38', label: 'SECRETARÍA DE GOBIERNO' },
  { value: '39', label: 'SECRETARÍA DE LA CONTRALORÍA' },
  { value: '40', label: 'SECRETARÍA DE LA JUVENTUD' },
  { value: '41', label: 'SECRETARÍA DE PLANEACIÓN Y FINANZAS' },
  { value: '42', label: 'SECRETARÍA DE SALUD' },
  { value: '43', label: 'SECRETARÍA DE SEGURIDAD CIUDADANA' },
  { value: '44', label: 'SECRETARÍA DE TURISMO' },
  { value: '45', label: 'SECRETARÍA DEL TRABAJO' },
  { value: '46', label: 'SECRETARÍA DEL TRANSPORTE' },
  { value: '47', label: 'SISTEMA ESTATAL DE COMUNICACION CULTURAL Y EDUCATIVA' },
  { value: '48', label: 'CASA QUERETANA DE LAS ARTESANÍAS' },
  { value: '49', label: 'COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS DEL ESTADO' },
  { value: '50', label: 'COORDINACION DE COMUNICACIÓN SOCIAL' },
  { value: '51', label: 'DIRECCIÓN DE DESARROLLO INTEGRAL DE LA FAMILIA' },
  { value: '52', label: 'DIRECCIÓN DEL REGISTRO PUBLICO DE LA PROPIEDAD' },
  { value: '53', label: 'DIRECCIÓN GENERAL DEL REGISTRO CIVIL' },
  { value: '54', label: 'ESCUELA NORMAL DEL ESTADO' },
  { value: '55', label: 'ESCUELA NORMAL SUPERIOR DE QUERETARO' },
  { value: '56', label: 'INSTITUTO DE CAPACITACION PARA EL TRABAJO DEL ESTADO DE QUERETARO' },
  { value: '57', label: 'INSTITUTO DEL DEPORTE Y LA RECREACION DEL ESTADO DE QUERETARO' },
  { value: '58', label: 'INSTITUTO QUERETANO DE LA CULTURA Y LAS ARTES' },
  { value: '59', label: 'OFICIALÍA MAYOR' },
  { value: '60', label: 'PROCURADURIA GENERAL DE JUSTICIA' },
  { value: '61', label: 'SECRETARÍA DE CULTURA' },
  { value: '62', label: 'SECRETARÍA DE DESARROLLO AGROPECUARIO' },
  { value: '63', label: 'SECRETARÍA DE DESARROLLO SUSTENTABLE' },
  { value: '64', label: 'SECRETARÍA DE DESARROLLO URBANO Y OBRAS PÚBLICAS' },
  { value: '65', label: 'SECRETARÍA DE EDUCACIÓN' },
  { value: '66', label: 'SECRETARÍA DE GOBIERNO' },
  { value: '67', label: 'SECRETARÍA DE LA CONTRALORÍA' },
  { value: '68', label: 'SECRETARÍA DE LA JUVENTUD' },
  { value: '69', label: 'SECRETARÍA DE PLANEACIÓN Y FINANZAS' },
  { value: '70', label: 'SECRETARÍA DE SALUD' },
  { value: '71', label: 'SECRETARÍA DE SEGURIDAD CIUDADANA' },
  { value: '72', label: 'SECRETARÍA DE TURISMO' },
  { value: '73', label: 'SECRETARÍA DEL TRABAJO' },
  { value: '74', label: 'SECRETARÍA DEL TRANSPORTE' },
  { value: '75', label: 'SISTEMA ESTATAL DE COMUNICACION CULTURAL Y EDUCATIVA' },
];